//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer.LibraryCore.ServiceReferenceCore
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerCore", Namespace="http://schemas.datacontract.org/2004/07/Customer.DataLayerCore")]
    public partial class CustomerCore : object
    {
        
        private int CustomerIdField;
        
        private string CustomerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Customer.LibraryCore.ServiceReferenceCore.ICustomerServiceCore")]
    public interface ICustomerServiceCore
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServiceCore/CustomerList", ReplyAction="http://tempuri.org/ICustomerServiceCore/CustomerListResponse")]
        System.Threading.Tasks.Task<Customer.LibraryCore.ServiceReferenceCore.CustomerCore[]> CustomerListAsync(Customer.LibraryCore.ServiceReferenceCore.CustomerCore customer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ICustomerServiceCoreChannel : Customer.LibraryCore.ServiceReferenceCore.ICustomerServiceCore, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CustomerServiceCoreClient : System.ServiceModel.ClientBase<Customer.LibraryCore.ServiceReferenceCore.ICustomerServiceCore>, Customer.LibraryCore.ServiceReferenceCore.ICustomerServiceCore
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerServiceCoreClient() : 
                base(CustomerServiceCoreClient.GetDefaultBinding(), CustomerServiceCoreClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICustomerServiceCore.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceCoreClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerServiceCoreClient.GetBindingForEndpoint(endpointConfiguration), CustomerServiceCoreClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceCoreClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerServiceCoreClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceCoreClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerServiceCoreClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceCoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Customer.LibraryCore.ServiceReferenceCore.CustomerCore[]> CustomerListAsync(Customer.LibraryCore.ServiceReferenceCore.CustomerCore customer)
        {
            return base.Channel.CustomerListAsync(customer);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerServiceCore))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerServiceCore))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5153/CustomerServiceCore.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomerServiceCoreClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICustomerServiceCore);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomerServiceCoreClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICustomerServiceCore);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICustomerServiceCore,
        }
    }
}
