//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/CustomerService.Data")]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        private string CustomerNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICustomers")]
public interface ICustomers
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/CustomerList", ReplyAction="http://tempuri.org/ICustomers/CustomerListResponse")]
    CustomerService.Data.Customer[] CustomerList(CustomerService.Data.Customer customer);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/CustomerList", ReplyAction="http://tempuri.org/ICustomers/CustomerListResponse")]
    System.Threading.Tasks.Task<CustomerService.Data.Customer[]> CustomerListAsync(CustomerService.Data.Customer customer);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICustomersChannel : ICustomers, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CustomersClient : System.ServiceModel.ClientBase<ICustomers>, ICustomers
{
    
    public CustomersClient()
    {
    }
    
    public CustomersClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CustomersClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CustomersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CustomersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CustomerService.Data.Customer[] CustomerList(CustomerService.Data.Customer customer)
    {
        return base.Channel.CustomerList(customer);
    }
    
    public System.Threading.Tasks.Task<CustomerService.Data.Customer[]> CustomerListAsync(CustomerService.Data.Customer customer)
    {
        return base.Channel.CustomerListAsync(customer);
    }
}
